name: CD - Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "k8s/**"
      - ".github/workflows/cd.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_AKS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: rg-devsecops-p2
          cluster-name: aks-devsecops-p2

      - name: Install kubelogin
        run: |
          sudo apt-get update
          sudo apt-get install -y kubelogin

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/staging/ -n staging
          kubectl rollout status deployment/devsecops-deployment -n staging --timeout=120s

      - name: Show status
        if: always()
        run: |
          kubectl get pods -n staging
          kubectl get svc -n staging
